steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/helloworldnode', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/helloworldnode']
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
   - "deploy" 
   - "apply" 
   - "--file=clouddeploy.yaml"
   - "--region=us-central1"
   - "--project=tribally-host-prj-s1"
options:
  logging: CLOUD_LOGGING_ONLY
