steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/${PROJECT_ID}/helloworldnode', '.']
- name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'eu.gcr.io/${PROJECT_ID}/helloworldnode']

options:
  logging: CLOUD_LOGGING_ONLY
