apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-qs-dev
spec:
  template:
    spec:
      containers:
      - image: gcr.io/tribally-host-prj-s1/helloworldnode
        ports:
        - containerPort: 4000
