apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: myapp
deploy:
  cloudrun: {}
profiles:
  - name: dev #should match with cloudeploy profiles
    manifests:
      rawYaml:
        - cloud-deploy-run-yamls/myapp-dev.yaml
